In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('D:\\NationalNames.csv')

1. Виведіть перші 8 рядків набору даних.

In [23]:
df.head(8)

   Id       Name  Year Gender  Count
0   1       Mary  1880      F   7065
1   2       Anna  1880      F   2604
2   3       Emma  1880      F   2003
3   4  Elizabeth  1880      F   1939
4   5     Minnie  1880      F   1746
5   6   Margaret  1880      F   1578
6   7        Ida  1880      F   1472
7   8      Alice  1880      F   1414

3. Отримайте імена стовпців набору даних

In [14]:
df.columns

Index(['Id', 'Name', 'Year', 'Gender', 'Count'], dtype='object')

6. Обчисліть кількість унікальних жіночих та чоловічих імен у цілому наборі даних

In [51]:
df.groupby(['Gender'])['Name'].nunique().reset_index()

  Gender   Name
0      F  64911
1      M  39199

7. Знайдіть 5 найпопулярніших чоловічих імен у 2010 році

In [4]:
df[(df['Year'] == 2010) & (df['Gender'] == 'M')].head()

              Id     Name  Year Gender  Count
1677392  1677393    Jacob  2010      M  22082
1677393  1677394    Ethan  2010      M  17985
1677394  1677395  Michael  2010      M  17308
1677395  1677396   Jayden  2010      M  17152
1677396  1677397  William  2010      M  17030

8. Знайдіть найпопулярніше ім’я за результатами одного року (ім’я, для якого
Count максимальне)

In [35]:
name=df.loc[df['Count'].idxmax(), 'Name']
year=df.loc[df['Count'].idxmax(), 'Year']
print('The name is '+name+' in '+str(year))

The name is Linda in 1947

12. Знайдіть найпопулярніше ім’я в році з найбільшою кількістю унікальних
імен (тобто у 2008 році)

In [24]:
year=df.groupby('Year')['Name'].nunique().idxmax()
df[df['Year'] == 2008].sort_values(by='Count').iloc[-1]['Name']

'Jacob'

In [ ]:
13. Знайдіть рік, коли ім’я “Jacob” було найпопулярнішим серед жіночих
імен

In [24]:
df[(df['Name'] == 'Jacob') & (df['Gender'] == 'F')].nlargest(1, 'Count')

              Id   Name  Year Gender  Count
1455556  1455557  Jacob  2004      F    171

In [ ]:
14. Знайти рік із найбільшою кількістю гендерно нейтральних імен (однакові
чоловічі та жіночі імена)

In [27]:
group = df.groupby(['Year', 'Name', 'Gender']).size().unstack()
gender = (group['F'] > 0) & (group['M'] > 0)
sumy = gender.groupby('Year').sum()
year = sumy.idxmax()
count = sumy.max()
res = pd.DataFrame({'Year': [year], 'Gender_neutral_names': [count]})
res

   Year  Gender_neutral_names
0  2008                  2557

In [ ]:
15. Знайдіть загальну кількість народжень за рік.

In [49]:
df.groupby('Year')['Count'].sum().reset_index()

     Year    Count
0    1880   201484
1    1881   192699
2    1882   221538
3    1883   216950
4    1884   243467
..    ...      ...
130  2010  3686589
131  2011  3646730
132  2012  3643336
133  2013  3626802
134  2014  3670151

[135 rows x 2 columns]

In [ ]:
16. Знайдіть рік, коли народилося найбільше дітей

In [61]:
tot= df.groupby('Year')['Count'].sum()
year = tot.idxmax()
year

1957

In [ ]:
17. Знайдіть кількість дівчаток та хлопчиків, які народились кожного року

In [67]:
res = df.groupby(['Year', 'Gender'])['Count'].sum().unstack()
res

Gender        F        M
Year
1880      90993   110491
1881      91954   100745
1882     107850   113688
1883     112321   104629
1884     129022   114445
...         ...      ...
2010    1772738  1913851
2011    1753500  1893230
2012    1753922  1889414
2013    1745339  1881463
2014    1768775  1901376

[135 rows x 2 columns]

In [ ]:
19. Підрахуйте кількість гендерно нейтральних імен (однакових для дівчат та
хлопців)

In [72]:
(df.groupby('Name')['Gender'].nunique()==2).sum()

10221

In [ ]:
20. Порахуйте, скільки разів хлопчиків називали Barbara

In [71]:
 df[(df['Name'] == 'Barbara') & (df['Gender'] == 'M')]['Count'].sum()

4139

In [ ]:
22. Знайти найпопулярніші гендерно-нейтральні імена (ті, що присутні
кожного року)

In [46]:
names = {}
M = df[df['Gender'] == 'M'].groupby('Year')['Name'].unique()
F = df[df['Gender'] == 'F'].groupby('Year')['Name'].unique()
for name in df['Year'].unique():
    names[name] = set(M[name]) & set(F[name])
all = set.intersection(*names.values())
popular = pd.DataFrame({'0': list(all)})
popular

          0
0    Joseph
1    Leslie
2    Marion
3   Francis
4    Sidney
5      John
6       Lee
7      Jean
8     Ollie
9     Jesse
10  William
11   Jessie
12   Robert
13   Tommie
14  Johnnie
15    James

In [ ]:
24. Знайти найпопулярніші імена в кожному році.

In [14]:
sumn = df.groupby(['Year', 'Name'])['Count'].sum().reset_index()
id = sumn.groupby('Year')['Count'].idxmax()
res = sumn.loc[id]
res[['Year', 'Name', 'Count']]

         Year      Name  Count
955      1880      John   9701
2818     1881      John   8795
4735     1882      John   9597
6727     1883      John   8934
8775     1884      John   9428
...       ...       ...    ...
1521288  2010  Isabella  22913
1568092  2011    Sophia  21839
1599369  2012    Sophia  22285
1630271  2013    Sophia  21172
1643629  2014      Emma  20811

[135 rows x 3 columns]